version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./df-backend
    ports:
      - 5050:5050
      - 5051:5051
    volumes:
      - ./backend:/backend
    networks:
      - my_network

  ml-endpoint:
    build:
      context: .
      dockerfile: ./df-ml-endpoint
    ports:
      - 8000:8000
    volumes:
      - ./ml-endpoint:/ml-endpoint
    networks:
      - my_network

  frontend:
    build:
      context: .
      dockerfile: ./df-frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend
    networks:
      - my_network
    environment:
      - VITE_DOMAIN=http://localhost:5050
      - VITE_SOCKET_DOMAIN=http://localhost:5051

networks:
  my_network:
    driver: bridge
